---
- name: My test playbook
  hosts: webservers
  become: true

  tasks:
   - name: to install httpd pkg
     yum: 
      name: httpd
      state: present

   - name: start httpd service
     service:
      name: httpd
      state: started    


